footprint: [[0.12, 0.14], [0.12, -0.14], [-0.12, -0.14], [-0.12, 0.14]]

transform_tolerance: 0.2
global_frame: map
robot_base_frame: base_link

subscribe_to_updates: true

obstacle_layer:
 enabled: true
 obstacle_range: 7.5 
 raytrace_range: 8.5
 track_unknown_space: false
 combination_method: 1


observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}

always_send_full_costmap: true

static_layer:
  enabled:              true
  map_topic:            "/map"
